import type { Metadata } from "next";
import type React from "react";

import Navbar from "@/components/Navbar";
import { Rubik } from "next/font/google";
import "./globals.css";

const mainFont = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
