export const dataDummyAnggota = [
  {
    id: 1,
    nama: "Mustafa Ali",
    foto: "path/to/photo1.jpg",
    jabatan: "Anggota",
    divisi: "Front-end",
  },
  {
    id: 2,
    nama: "Siti Rahma",
    foto: "path/to/photo2.jpg",
    jabatan: "Ketua",
    divisi: "Back-end",
  },
  {
    id: 3,
    nama: "Budi Santoso",
    foto: "path/to/photo3.jpg",
    jabatan: "Wakil Ketua",
    divisi: "DevOps",
  },
  {
    id: 4,
    nama: "Dina Fitria",
    foto: "path/to/photo4.jpg",
    jabatan: "Anggota",
    divisi: "Design",
  },
  {
    id: 5,
    nama: "Eko Prabowo",
    foto: "path/to/photo5.jpg",
    jabatan: "Anggota",
    divisi: "Marketing",
  },
  {
    id: 6,
    nama: "Rina Sari",
    foto: "path/to/photo6.jpg",
    jabatan: "Anggota",
    divisi: "Content",
  },
  {
    id: 7,
    nama: "Tariq Fadly",
    foto: "path/to/photo7.jpg",
    jabatan: "Ketua",
    divisi: "UI/UX",
  },
  {
    id: 8,
    nama: "Winda Yuliana",
    foto: "path/to/photo8.jpg",
    jabatan: "Wakil Ketua",
    divisi: "QA",
  },
  {
    id: 9,
    nama: "Fajar Nugroho",
    foto: "path/to/photo9.jpg",
    jabatan: "Anggota",
    divisi: "Support",
  },
  {
    id: 10,
    nama: "Lina Rahmadani",
    foto: "path/to/photo10.jpg",
    jabatan: "Anggota",
    divisi: "Project Management",
  },
  {
    id: 11,
    nama: "Arief Hadi",
    foto: "path/to/photo11.jpg",
    jabatan: "Anggota",
    divisi: "Security",
  },
  {
    id: 12,
    nama: "Nina Kartika",
    foto: "path/to/photo12.jpg",
    jabatan: "Ketua",
    divisi: "HR",
  },
  {
    id: 13,
    nama: "Joko Widodo",
    foto: "path/to/photo13.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Finance",
  },
  {
    id: 14,
    nama: "Rika Puspitasari",
    foto: "path/to/photo14.jpg",
    jabatan: "Anggota",
    divisi: "Legal",
  },
  {
    id: 15,
    nama: "Dedi Kusnadi",
    foto: "path/to/photo15.jpg",
    jabatan: "Anggota",
    divisi: "Operations",
  },
  {
    id: 16,
    nama: "Dewi Lestari",
    foto: "path/to/photo16.jpg",
    jabatan: "Anggota",
    divisi: "Research",
  },
  {
    id: 17,
    nama: "Hadi Prayogo",
    foto: "path/to/photo17.jpg",
    jabatan: "Ketua",
    divisi: "Sales",
  },
  {
    id: 18,
    nama: "Maya Sari",
    foto: "path/to/photo18.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Customer Service",
  },
  {
    id: 19,
    nama: "Rudi Santoso",
    foto: "path/to/photo19.jpg",
    jabatan: "Anggota",
    divisi: "Training",
  },
  {
    id: 20,
    nama: "Bella Kurnia",
    foto: "path/to/photo20.jpg",
    jabatan: "Anggota",
    divisi: "Strategy",
  },
  {
    id: 21,
    nama: "Agus Prabowo",
    foto: "path/to/photo21.jpg",
    jabatan: "Anggota",
    divisi: "IT",
  },
  {
    id: 22,
    nama: "Lia Nurul",
    foto: "path/to/photo22.jpg",
    jabatan: "Ketua",
    divisi: "Product",
  },
  {
    id: 23,
    nama: "Evi Wulandari",
    foto: "path/to/photo23.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Partnership",
  },
  {
    id: 24,
    nama: "Hendra Sulaiman",
    foto: "path/to/photo24.jpg",
    jabatan: "Anggota",
    divisi: "Quality Assurance",
  },
  {
    id: 25,
    nama: "Novi Rahmat",
    foto: "path/to/photo25.jpg",
    jabatan: "Anggota",
    divisi: "Media",
  },
  {
    id: 26,
    nama: "Rina Marlina",
    foto: "path/to/photo26.jpg",
    jabatan: "Anggota",
    divisi: "Event",
  },
  {
    id: 27,
    nama: "Dedi Haryanto",
    foto: "path/to/photo27.jpg",
    jabatan: "Ketua",
    divisi: "Logistics",
  },
  {
    id: 28,
    nama: "Fiona Sabrina",
    foto: "path/to/photo28.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Branding",
  },
  {
    id: 29,
    nama: "Santo Setiawan",
    foto: "path/to/photo29.jpg",
    jabatan: "Anggota",
    divisi: "Customer Experience",
  },
  {
    id: 30,
    nama: "Vina Nuraini",
    foto: "path/to/photo30.jpg",
    jabatan: "Anggota",
    divisi: "Training & Development",
  },
  {
    id: 31,
    nama: "Rudi Setiawan",
    foto: "path/to/photo31.jpg",
    jabatan: "Anggota",
    divisi: "Engineering",
  },
  {
    id: 32,
    nama: "Lisa Sari",
    foto: "path/to/photo32.jpg",
    jabatan: "Ketua",
    divisi: "Design",
  },
  {
    id: 33,
    nama: "Tommy Prasetyo",
    foto: "path/to/photo33.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Digital Marketing",
  },
  {
    id: 34,
    nama: "Lina Alifah",
    foto: "path/to/photo34.jpg",
    jabatan: "Anggota",
    divisi: "Research & Development",
  },
  {
    id: 35,
    nama: "Dian Puspita",
    foto: "path/to/photo35.jpg",
    jabatan: "Anggota",
    divisi: "Business Development",
  },
  {
    id: 36,
    nama: "Anwar Ibrahim",
    foto: "path/to/photo36.jpg",
    jabatan: "Anggota",
    divisi: "Customer Support",
  },
  {
    id: 37,
    nama: "Rina Kurnia",
    foto: "path/to/photo37.jpg",
    jabatan: "Ketua",
    divisi: "Accounting",
  },
  {
    id: 38,
    nama: "Eko Rudi",
    foto: "path/to/photo38.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Project Management",
  },
  {
    id: 39,
    nama: "Ayu Lestari",
    foto: "path/to/photo39.jpg",
    jabatan: "Anggota",
    divisi: "Operations",
  },
  {
    id: 40,
    nama: "Hana Nur",
    foto: "path/to/photo40.jpg",
    jabatan: "Anggota",
    divisi: "HR",
  },
  {
    id: 41,
    nama: "Fadli Nurcahyo",
    foto: "path/to/photo41.jpg",
    jabatan: "Ketua",
    divisi: "Sales & Marketing",
  },
  {
    id: 42,
    nama: "Dewi Sari",
    foto: "path/to/photo42.jpg",
    jabatan: "Wakil Ketua",
    divisi: "Design",
  },
  {
    id: 43,
    nama: "Ricky Setiawan",
    foto: "path/to/photo43.jpg",
    jabatan: "Anggota",
    divisi: "Business Intelligence",
  },
  {
    id: 44,
    nama: "Siska Putri",
    foto: "path/to/photo44.jpg",
    jabatan: "Anggota",
    divisi: "Digital Strategy",
  },
  {
    id: 45,
    nama: "Benny Wijaya",
    foto: "path/to/photo45.jpg",
    jabatan: "Anggota",
    divisi: "Customer Insights",
  },
  {
    id: 46,
    nama: "Ria Marliana",
    foto: "path/to/photo46.jpg",
    jabatan: "Ketua",
    divisi: "Technical Support",
  },
  {
    id: 47,
    nama: "Dika Putra",
    foto: "path/to/photo47.jpg",
    jabatan: "Wakil Ketua",
    divisi: "E-commerce",
  },
  {
    id: 48,
    nama: "Mira Ayu",
    foto: "path/to/photo48.jpg",
    jabatan: "Anggota",
    divisi: "Content Marketing",
  },
  {
    id: 49,
    nama: "Rizky Halim",
    foto: "path/to/photo49.jpg",
    jabatan: "Anggota",
    divisi: "Data Science",
  },
  {
    id: 50,
    nama: "Nita Dewi",
    foto: "path/to/photo50.jpg",
    jabatan: "Anggota",
    divisi: "Innovation",
  },
];
