export const dataStrukturBPH = [
  {
    id: 1,
    gambar: "/pencapaian-gambar-1.svg",
    nama: "Nama",
    jabatan: "Ketua 1",
    divisi: "Front-End",
  },
  {
    id: 2,
    gambar: "/pencapaian-gambar-1.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 1",
  },
  {
    id: 3,
    gambar: "/pencapaian-gambar-2.svg",
    nama: "Nama",
    jabatan: "Ketua 2",
    divisi: "Back-End",
  },
  {
    id: 4,
    gambar: "/pencapaian-gambar-2.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 2",
  },
  {
    id: 5,
    gambar: "/pencapaian-gambar-3.svg",
    nama: "Nama",
    jabatan: "Ketua 3",
    divisi: "Security",
  },
  {
    id: 6,
    gambar: "/pencapaian-gambar-3.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 3",
  },
  {
    id: 7,
    gambar: "/pencapaian-gambar-1.svg",
    nama: "Nama",
    jabatan: "Ketua 4",
    divisi: "Multimedia",
  },
  {
    id: 8,
    gambar: "/pencapaian-gambar-1.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 4",
  },
  {
    id: 9,
    gambar: "/pencapaian-gambar-2.svg",
    nama: "Nama",
    jabatan: "Ketua 5",
    divisi: "Humas",
  },
  {
    id: 10,
    gambar: "/pencapaian-gambar-2.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 5",
  },
  {
    id: 11,
    gambar: "/pencapaian-gambar-3.svg",
    nama: "Nama",
    jabatan: "Ketua 6",
    divisi: "Internal",
  },
  {
    id: 12,
    gambar: "/pencapaian-gambar-3.svg",
    nama: "Nama",
    jabatan: "Wakil Ketua 6",
  },
];
